version: '3.8'

services:
  music-aggregator-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: music-aggregator-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - SERVER_PASSWORD=${SERVER_PASSWORD:-change-me-in-production}
      - CACHE_TTL=3600
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:3000}
    volumes:
      - ./backend/data:/app/data
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - music-network

  # YouTube PO Token Provider (Required for October 2025+ YouTube bot protection)
  po-token-provider:
    image: brainicism/bgutil-ytdlp-pot-provider:latest
    container_name: youtube-po-token-provider
    ports:
      - "4416:4416"
    restart: unless-stopped
    init: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4416/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - music-network

networks:
  music-network:
    driver: bridge

volumes:
  music-data: