"""
Audio Streaming Service v2.0
Handles YouTube audio streaming using yt-dlp with cookie authentication
"""
import logging
from typing import Dict, Any, Optional
import yt_dlp
import os
import tempfile

logger = logging.getLogger(__name__)


class AudioStreamingService:
    """Service for streaming YouTube audio with cookie authentication"""
    
    def __init__(self, cookie: Optional[str] = None):
        """
        Initialize the audio streaming service
        
        Args:
            cookie: YouTube Music cookie string for authentication
        """
        self.cache = {}
        self.cookie = cookie
        self.cookie_file = None
        
        if self.cookie:
            self._create_cookie_file()
    
    def _create_cookie_file(self):
        """Create a temporary cookie file for yt-dlp in Netscape format"""
        try:
            self.cookie_file = tempfile.NamedTemporaryFile(
                mode='w', 
                suffix='.txt',
                delete=False
            )
            
            # Write Netscape cookie header
            self.cookie_file.write("# Netscape HTTP Cookie File\n")
            self.cookie_file.write("# This file is generated by yt-dlp.  Do not edit.\n\n")
            
            # Parse cookie string and write in proper Netscape format
            # Format: domain	flag	path	secure	expiration	name	value
            cookie_pairs = self.cookie.split('; ')
            
            for pair in cookie_pairs:
                if '=' in pair:
                    name, value = pair.split('=', 1)
                    
                    # Determine if this is a secure cookie
                    is_secure = name.startswith('__Secure-') or name.startswith('__Host-')
                    secure_flag = 'TRUE' if is_secure else 'FALSE'
                    
                    # Set expiration far in the future (10 years)
                    expiration = '2000000000'
                    
                    # Write for both youtube.com and music.youtube.com
                    self.cookie_file.write(
                        f".youtube.com\tTRUE\t/\t{secure_flag}\t{expiration}\t{name}\t{value}\n"
                    )
                    self.cookie_file.write(
                        f".music.youtube.com\tTRUE\t/\t{secure_flag}\t{expiration}\t{name}\t{value}\n"
                    )
            
            self.cookie_file.close()
            logger.info(f"[AudioStream] Created cookie file with {len(cookie_pairs)} cookies")
            
        except Exception as e:
            logger.error(f"[AudioStream] Failed to create cookie file: {e}")
            self.cookie_file = None
        
    async def get_stream_url(self, video_id: str) -> Optional[Dict[str, Any]]:
        """
        Get the direct stream URL for a YouTube video
        
        Args:
            video_id: YouTube video ID
            
        Returns:
            Dictionary with stream info or None
        """
        try:
            logger.info(f"[AudioStream] Getting stream URL for: {video_id}")
            
            ydl_opts = {
                'format': 'bestaudio/best',
                'quiet': True,
                'no_warnings': True,
                'extract_flat': False,
                'nocheckcertificate': True,
                'no_check_certificate': True,
                'age_limit': None,
                'http_headers': {
                    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
                    'Accept-Language': 'en-us,en;q=0.5',
                    'Accept-Encoding': 'gzip, deflate',
                    'Referer': 'https://www.youtube.com/',
                },
            }
            
            # Try with cookie file if available, but don't fail if cookies don't work
            if self.cookie_file and os.path.exists(self.cookie_file.name):
                try:
                    ydl_opts['cookiefile'] = self.cookie_file.name
                    logger.info(f"[AudioStream] Attempting authentication with cookie file")
                except Exception as e:
                    logger.warning(f"[AudioStream] Cookie file not working, continuing without: {e}")
            
            # Always use regular YouTube (works without authentication)
            # Music URLs require authentication even with cookies
            url = f"https://www.youtube.com/watch?v={video_id}"
            
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                info = ydl.extract_info(url, download=False)
                
                if not info:
                    logger.error(f"[AudioStream] No info returned for {video_id}")
                    return None
                
                formats = info.get('formats', [])
                
                if not formats:
                    logger.error(f"[AudioStream] No formats available for {video_id}")
                    return None
                
                audio_formats = [
                    f for f in formats 
                    if f.get('acodec') != 'none' and f.get('vcodec') == 'none'
                ]
                
                if not audio_formats:
                    logger.warning(f"[AudioStream] No audio-only formats, using all formats")
                    audio_formats = formats
                
                audio_formats.sort(
                    key=lambda x: (x.get("abr") or x.get("tbr") or 0),
                    reverse=True
                )
                
                best_format = audio_formats[0]
                stream_url = best_format.get('url')
                
                if not stream_url:
                    logger.error(f"[AudioStream] No stream URL in format")
                    return None
                
                logger.info(f"[AudioStream] ✓ Got stream URL (format: {best_format.get('format_id')}, bitrate: {best_format.get('abr')})")
                
                return {
                    'url': stream_url,
                    'format_id': best_format.get('format_id'),
                    'ext': best_format.get('ext'),
                    'bitrate': best_format.get('abr') or best_format.get('tbr'),
                    'duration': info.get('duration'),
                    'title': info.get('title')
                }
                
        except Exception as e:
            logger.error(f"[AudioStream] Error: {e}")
            return None
    
    def __del__(self):
        """Cleanup cookie file on deletion"""
        if self.cookie_file and os.path.exists(self.cookie_file.name):
            try:
                os.unlink(self.cookie_file.name)
                logger.info(f"[AudioStream] Cleaned up cookie file")
            except Exception as e:
                logger.error(f"[AudioStream] Failed to cleanup cookie file: {e}")
