version: '3.8'

services:
  ipod-music-backend:
    build: .
    container_name: ipod-music-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Mount keys directory if using Apple Music
      - ./keys:/app/keys:ro
    networks:
      - ipod-music-network

networks:
  ipod-music-network:
    driver: bridge
